name: chat_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  fluttertoast: ^8.2.10
  cloud_firestore: ^5.6.1
  intl: ^0.20.1
  image_picker: ^1.1.2
  cloudinary_flutter: ^1.3.0
  cloudinary_public: ^0.23.1
  cloudinary_sdk: ^5.0.0+1
  mime: ^1.0.0
  http: 1.2.2
  onesignal_flutter: ^5.2.9
  flutter_local_notifications: ^18.0.1
  flutter_sound: ^9.19.1
  audio_waveforms: ^1.2.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
